### ISSUE TITLE
Failed to run cudaGetDeviceCount() with pytorch-gpgpu-sim

### ISSUE THREAD

**Issue by RedCarrottt** [gpgpu-sim/gpgpu-sim_distribution#110]
# Used Environments
* Ubuntu 16.04.5
* CUDA 8.0
* cuDNN 7.1.4
* gcc 5.4.0
* g++ 5.4.0
* python 2.7.12

# Problem Situation
Hello, I am trying to run pytorch-gpgpu-sim with gpgpu-sim_distribution dev branch.

I've built gpgpu-sim_distribution and pytorch-gpgpu-sim successfully.

However, I could not run my PyTorch model.

When I'm trying to run it, the PyTorch is terminated with following message.

```
THCudaCheck FAIL file=/home/redcarrottt/pytorch-gpgpu-sim/aten/src/THC/THCGeneral.cpp line=74 error=30 : unknown error
Traceback (most recent call last):
  File "./infer.py", line 130, in <module>
    infer(net, args)
  File "./infer.py", line 47, in infer
    net_gpu = net.cuda()
  File "/home/redcarrottt/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 258, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/redcarrottt/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 185, in _apply
    module._apply(fn)
  File "/home/redcarrottt/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 191, in _apply
    param.data = fn(param.data)
  File "/home/redcarrottt/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 258, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: cuda runtime error (30) : unknown error at /home/redcarrottt/pytorch-gpgpu-sim/aten/src/THC/THCGeneral.cpp:74
```

As I know, the CUDA function which makes the error is ```cudaGetDeviceCount()```.
(called at ```aten/src/THC/THCGeneral.cpp:74```)

I guess that my PyTorch's linking configuration is wrong.

Anyone knows what is the exact reason?
Thank you.

**Comment by RedCarrottt** [comment]
I solved the problem by myself.
It was caused because of environment value settings.
After I set following values, I could run it successfully.
* ```LD_LIBRARY_PATH```
* ```CUDA_INSTALL_PATH```
* ```PYTORCH_BIN```
