### ISSUE TITLE
Fail to prune PTX section list

### ISSUE THREAD

**Issue by RedCarrottt** [gpgpu-sim/gpgpu-sim_distribution#111]
# Used Environments
* Ubuntu 16.04.5
* CUDA 8.0
* cuDNN 7.1.4
* gcc 5.4.0
* g++ 5.4.0
* python 2.7.12
* GPU: GTX 1080 Ti

# Problem Situation
Hello, I'm trying to run pytorch-gpgpu-sim but I'm facing a problem.

After it extract all the ptx files from ```libcudnn.so```, it fails to get pruned PTX section list as shown at following message.

```
Extracting PTX file and ptxas options  194: libcudnn.194.sm_50.ptx -arch=sm_50
Extracting specific PTX file named libcudnn.195.sm_61.ptx
Extracting PTX file and ptxas options  195: libcudnn.195.sm_61.ptx -arch=sm_61
Extracting specific PTX file named libcudnn.196.sm_35.ptx
Extracting PTX file and ptxas options  196: libcudnn.196.sm_35.ptx -arch=sm_35
Error: No PTX sections found with sm capability that is lower than current forced maximum capability
 minimum ptx capability found = 0, maximum forced ptx capability = 61
 User might want to change either the forced maximum capability from gpgpusim configuration or update the compilation to generate the required PTX version
```

I guess that I have problem in setting sm capability, but I don't know where I have to modify. 

https://github.com/gpgpu-sim/gpgpu-sim_distribution/blob/e5322e7bbe2c884b62aaecad0f854251c2187ba6/libcuda/cuda_runtime_api.cc#L2297-L2300

**Comment by RedCarrottt** [comment]
I solved this problem by myself.
After I set an environment value ```export CUOBJDUMP_SIM_FILE=on```, I could proceed this step successfully.
